[ServerInfo]
AddresIP=26.123.154.65
Game_Port = 5816
ServerName = CoPrivate
WebSite=

[InternetPort]
BackLog = 100
ReceiveSize = 8191
SendSize = 8191
;65000
[InterServer]
AddresIP=26.123.154.65
Port=9920
IsInterServer=0

[Database]
Location=Database5103\
CO2FOLDER=Database5103\
ItemUID=1156934
ClientUID=1101660
Day=64
[Tournaments]
PkWarWinner=1001082
